spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microsns?serverTimezone=Asia/Seoul
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  profiles:
    active: jpa

