CREATE TABLE IF NOT EXISTS board(
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) not null,
    content TEXT not null ,
    writer varchar(100) NOT NULL,
    password VARCHAR(100) NOT NULL ,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    modified_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS comment(
    id BIGINT NOT NULL AUTO_INCREMENT,
    board_id BIGINT,
    writer VARCHAR(100) NOT NULL ,
    content TEXT NOT NULL ,
    password VARCHAR(100) NOT NULL ,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    modified_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    FOREIGN KEY (board_id) REFERENCES board(id) ON DELETE CASCADE
);